### ISSUE TITLE
include <Eigen/Eigen> couldn't be located

### ISSUE THREAD

**Issue by YingfangZhou** [OPM/opm-polymer#126] opened 2015-06-10 23:42 UTC
yz7609@ese-zhou:~/OPM/opm-polymer-build$ make
[  5%] Patching Makefile to be DUNE compatible
[  5%] Built target dune-compat
[ 10%] Updating version information
[ 10%] Built target update-version
[ 15%] Building CXX object CMakeFiles/opmpolymer.dir/opm/polymer/fullyimplicit/PolymerPropsAd.cpp.o
In file included from /home/yz7609/opm-polymer/opm/polymer/fullyimplicit/PolymerPropsAd.cpp:24:0:
/usr/local/include/opm/autodiff/AutoDiffBlock.hpp:25:23: fatal error: Eigen/Eigen: No such file or directory
 #include <Eigen/Eigen>
                       ^
compilation terminated.
make[2]: *** [CMakeFiles/opmpolymer.dir/opm/polymer/fullyimplicit/PolymerPropsAd.cpp.o] Error 1
make[1]: *** [CMakeFiles/opmpolymer.dir/all] Error 2
make: *** [all] Error 2

Any suggestion on this issue?

**Comment by atgeirr** [comment] 2015-06-15 08:01
This could be a duplicate of #94, so try to install Eigen separately, then rebuild opm-autodiff from scratch. The underlying problem is that opm-autodiff provides Eigen for itself if not found on the system, but this is not made visible to downstream modules such as opm-polymer.

**Comment by atgeirr** [comment] 2015-10-19 10:46
Closing this as a duplicate of #94.

**Closed by atgeirr** 2015-10-19 10:46 UTC
Labels: duplicate
